site_name: NLST Data Accessing API Documentation

nav:
  - Home: index.md
  - Documentation:
      - NLST Data Accessing: api/NLST_data_accessing.md
      - get_pid_paths: api/get_pid_paths.md
      - get_study_yr_series: api/get_study_yr_series.md
      - get_slice_paths: api/get_slice_paths.md
      - get_preference_rank: api/get_preference_rank.md
      - process_dicom_files: api/process_dicom_files.md
  - Contact Me: contact.md

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google


markdown_extensions:
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - admonition