site_name: NLST Data Accessing API Documentation

nav:
  - Home: index.md
  - API Documentation:
      - NLST Data Accessing: api/NLST_data_accessing.md
      - Get PID Paths: api/get_pid_paths.md
      - Get Study Year Series: api/get_study_yr_series.md
      - Get Slice Paths: api/get_slice_paths.md
      - Get Preference Rank: api/get_preference_rank.md
      - Process DICOM Files: api/process_dicom_files.md
  - Contact Me: contact.md

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google


markdown_extensions:
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - admonition